import type { NextPage } from 'next';
import Head from 'next/head';
import FloatingFooter from '../../components/FloatingFooter';
import Navbar from '../../components/Navbar';
import Image from 'next/future/image';
import AnimatedHero from '../../components/AnimatedHero';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Imarta - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="m-5">
        <div className="grid lg:grid-cols-2">
          <div>
            <div className="text-4xl mb-3">Sejarah IMARTA</div>
            <div className="text-xl mb-2">IMARTA - SKETSA</div>
            <div className="text-gray-400 font-light mb-3">
              IMARTA - SKETSA merupakan organisasi kemahasiswaan yang bertugas
              untuk mewadahi dan melayani IMARTA itu sendiri dengan prinsip dari
              mahasiswa oleh mahasiswa dan untuk mahasiswa. Kepengurusannya
              mengandung dua kata yaitu IMARTA dan SKETSA
            </div>
            <div className="ml-10 mb-2">
              <div className="text-lg">IMARTA</div>
              <div className="text-gray-400 font-light mb-2">
                IMARTA (Ikatan Mahasiswa Arsitektur Tarumanagara) mengartikan
                sebuah ikatan kekeluargaan yang terdiri dari seluruh mahasiswa
                arsitektur pada Program Studi S1 Arsitektur Universitas
                Tarumanagara, yang juga program studi tertua di Fakultas Teknik
                Universitas Tarumanagara
              </div>
            </div>
            <div className="ml-10 mb-3">
              <div className="text-lg">SKETSA</div>
              <div className="text-gray-400 font-light mb-2">
                SKETSA merupakan kebangaan IMARTA yaitu majalah arsitektur karya
                mahasiswa tertua di Indonesia yang resmi didirikan pada tahun
                1998
              </div>
            </div>
            <div className="mb-3 flex">
              <div className="flex-1">
                <Image
                  src="/logo-imarta.jpg"
                  width="0"
                  height="0"
                  sizes="100vw"
                  className="w-full h-24 object-contain"
                  alt="logo-imarta-about"
                />
              </div>
              <div className="flex-1">
                <Image
                  src="/logo-sketsa.png"
                  width="0"
                  height="0"
                  sizes="100vw"
                  className="w-full h-24 object-contain"
                  alt="logo-sketsa-about"
                />
              </div>
            </div>
            <div className="text-gray-400 font-light mb-3">
              IMARTA - SKETSA terdiri dari dua biro yang bekerja secara
              berdampingan pada setiap periodenya. Biro Umum merencanakan dan
              melaksanakan kegiatan-kegiatan baik secara akademis maupun non
              akademis. Sedangkan Biro Majalah yang menyusun dan memproduksi
              Majalah SKETSA
            </div>
          </div>
        </div>
      </div>
      <div className="my-5 bg-[#282828] p-5 lg:px-8 lg:py-12">
        <div className="text-2xl text-white mb-2">Makna Logo</div>
        <div className="flex flex-col lg:flex-row">
          <div className="flex-1 flex-col">
            <div className="text-white mb-2">
              <span className="font-medium">Huruf &quot;H&quot;</span>{' '}
              <span className="font-light">
                berposisi di atas mengartikan sebagai HIMPUNAN yang selalu
                berkembang menuju pengharapan warna putih, &quot;jiwa yang
                bersih&quot;
              </span>
            </div>
            <div className="text-white mb-2">
              <span className="font-medium">Huruf &quot;I&quot;</span>{' '}
              <span className="font-light">
                megartikan kata pertama dari IMARTA yaitu IKATAN Kekeluargaan
                dari mahasiswa arsitektur Tarumanagara
              </span>
            </div>
            <div className="text-white mb-2">
              <span className="font-medium">
                Bidang bidang vertikal dan isonometri
              </span>{' '}
              <span className="font-light">
                logo melambangkan citra dari arsitektur
              </span>
            </div>
            <div className="text-white mb-2">
              <span className="font-medium">Dua bidang vertikal</span>{' '}
              <span className="font-light">
                di kanan mewakili kepengurusan IMARTA SKETSA ke dalam biro umum
                dan biro majalah yang setia berdampingan
              </span>
            </div>
            <div className="text-white mb-2">
              <span className="font-medium">Tarikan garis keseluruhan</span>{' '}
              <span className="font-light">
                yang berupa segi enam yang melambangkan perisai untuk selalu
                mempertahankan semua nilai-nilai dari Tri Dharma perguruan
                tinggi
              </span>
            </div>
          </div>
          <div className="flex-1 text-white">
            <div className="mb-4">
              <div className="font-medium">Penetapan Makna Logo:</div>
              <div className="flex">
                <div className="font-light flex-1">
                  2000/018/nol delapan belas
                </div>
                <div className="flex-1">
                  <div className="font-light">Gerald</div>
                  <div className="font-light">
                    Ketua Umum IMARTA SKETSA 2021/2022
                  </div>
                </div>
              </div>
            </div>
            <div className="mb-4">
              <div className="font-medium">Persetujuan:</div>
              <div className="flex mb-4">
                <div className="font-light flex-1">
                  1999/017/nol tujuh belas
                </div>
                <div className="flex-1">
                  <div className="font-light">Rafael Kelvin Herawan</div>
                  <div className="font-light">
                    Ketua Umum IMARTA SKETSA 2020/2021
                  </div>
                </div>
              </div>{' '}
              <div className="flex mb-4">
                <div className="font-light flex-1">1998/016/nol enam belas</div>
                <div className="flex-1">
                  <div className="font-light">Bryan Marco Wijaya</div>
                  <div className="font-light">
                    Ketua Umum IMARTA SKETSA 2019/2020
                  </div>
                </div>
              </div>{' '}
              <div className="flex mb-4">
                <div className="font-light flex-1">1997/015/nol lima belas</div>
                <div className="flex-1">
                  <div className="font-light">Indra Lesmana</div>
                  <div className="font-light">
                    Ketua Umum IMARTA SKETSA 2018/2019
                  </div>
                </div>
              </div>{' '}
            </div>
          </div>
        </div>
      </div>
      <AnimatedHero>
        <Image
          src="/logo-imarta-meaning.jpg"
          alt="logo-imarta-meaning"
          sizes="100vw"
          width="0"
          height="0"
          className="w-full h-auto"
        />
      </AnimatedHero>
      <FloatingFooter />
    </>
  );
};

export default About;
