import type { NextPage } from 'next';
import Head from 'next/head';
import FloatingFooter from '../components/FloatingFooter';
import HomeBanner from '../components/Homepage/HomeBanner';
import HomeHighlights from '../components/Homepage/HomeHighlights';
import HomeWelcome from '../components/Homepage/HomeWelcome';
import Navbar from '../components/Navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Imarta - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <img alt="hero" src="/homepage-hero.jpg" />
      <HomeWelcome />
      <HomeBanner
        title="Previous Event"
        timeline="PMB Arsitektur"
        description="Program Kerja Kolektif"
      />
      <HomeBanner
        title="Previous Event"
        timeline="PMB Arsitektur"
        description="Program Kerja Kolektif"
        isReversed
      />
      <HomeBanner
        title="Previous Event"
        timeline="PMB Arsitektur"
        description="Program Kerja Kolektif"
      />
      <HomeHighlights />
      <FloatingFooter />
    </>
  );
};

export default Home;
